### ISSUE TITLE
Update dep `@unstoppabledomains/resolution@7.1.2` to fix "Critical error" for webpack builds

### ISSUE THREAD

**Issue by tamagosante** [LIT-Protocol/lit-js-sdk#1]
## Background
- Project, that uses webpack(5)
- Encountered build issues
`critical dependency: the request of a dependency is an expression`

## Troubleshooting
- This repo uses package `"@unstoppabledomains/resolution": "^5.0.1",`
    - That version has above mentioned issue: https://github.com/unstoppabledomains/resolution/issues/150

## Solution
Update package to `@unstoppabledomains/resolution@7.1.2`
- As described by https://github.com/unstoppabledomains/resolution/issues/150#issuecomment-1006757827

## Steps to reproduce
- Clone repo https://github.com/hiaux0/webpack5-aurelia-please
- Checkout commit with issue (4th commit): 88e0bfbe2f5a61903c8c2b204d01346fa36b276f
- Verify commit with fix (5th commit): 479414e9908d4cf3645e7835169ab5b36d2162b9

**Comment by glitch003** [comment]
Thanks!  Fixed and released a new version of the SDK 1.1.117 that uses this updated package
