### ISSUE TITLE
Node.js SDK raises invalid JSON error

### ISSUE THREAD

**Issue by peddybeats** [LIT-Protocol/lit-js-sdk#2]
After successfully creating a signing condition using `saveSigningCondition` I'm trying to obtain and verify a JWT using `getSignedToken` and `verifyJwt` - I'm following [lit-only-serverside-sdk-example](https://github.com/LIT-Protocol/lit-only-serverside-sdk-example/blob/main/index.js).

When I call `getSignedToken` with payload [1], the client SDK produces log [2] and returns to me error [3].
Any idea why it thinks this JSON request payload is invalid? 

It's worth noting, I get a similar error [4] if in the example (the one I'm following) if I call /retrieve_and_verify before /store - this seems a bit odd - Instead of an error in JSON parsing, I'd expect an error like "no signing condition found at this path."

[1]
{"accessControlConditions":[{"contractAddress":"","standardContractType":"","chain":"ethereum","method":"eth_getBalance","parameters":[":userAddress","latest"],"returnValueTest":{"comparator":">=","value":"10000000000000"}}],"chain":"ethereum","authSig":{"sig":"0x39a3d6f2bedb5ef51442069d3c721596328ef50f81a3a0c0339c2acaade8bd721fea5cce0dc4acb6958cd40fddd680fb35c1fbd07fa95c7e657f5e6f154ed7fc1b","derivedVia":"web3.eth.personal.sign","signedMessage":"I am creating an account to use Lit Protocol at 2022-01-10T20:47:35.692Z","address":"0xfff175c14a299ef7027da0d348f438e154880ccd"},"resourceId":{"baseUrl":"https://wonderverse.xyz","path":"test_10","orgId":"","role":"","extraData":""}}

[2] 
sendCommandToNode with url https://node2.litgateway.com:7379/web/signing/retrieve and data {
  accessControlConditions: [
    {
      contractAddress: '',
      chain: 'ethereum',
      standardContractType: '',
      method: 'eth_getBalance',
      parameters: [Array],
      returnValueTest: [Object]
    }
  ],
  resourceId: {
    baseUrl: 'https://wonderverse.xyz',
    path: 'test_10',
    orgId: '',
    role: '',
    extraData: ''
  },
  authSig: {
    sig: '0x39a3d6f2bedb5ef51442069d3c721596328ef50f81a3a0c0339c2acaade8bd721fea5cce0dc4acb6958cd40fddd680fb35c1fbd07fa95c7e657f5e6f154ed7fc1b',
    derivedVia: 'web3.eth.personal.sign',
    signedMessage: 'I am creating an account to use Lit Protocol at 2022-01-10T20:47:35.692Z',
    address: '0xfff175c14a299ef7027da0d348f438e154880ccd'
  },
  chain: 'ethereum',
  iat: 1644793631,
  exp: 1644836831
}

[3]
"FetchError: invalid json response body at https://node2.litgateway.com:7376/web/signing/retrieve reason: Unexpected token < in JSON at position 0"

[4] 
FetchError: invalid json response body at https://node2.litgateway.com:7374/web/signing/retrieve reason: Unexpected token U in JSON at position 4

**Comment by glitch003** [comment]
Hey, apologies for the issues.  Our error messages are not great right now.  Can you share your code?  You can email it to me privately at chris@litprotocol.com if you want.

**Comment by peddybeats** [comment]
Just sent you an email!

**Comment by glitch003** [comment]
Hey, we put better error messages in, and I think this should be resolved now.  Please email me if not.  Thanks!
