### ISSUE TITLE
Error attempting to encryptFile

### ISSUE THREAD

**Issue by bryceeaton** [LIT-Protocol/lit-js-sdk#20]
Im attempting to to encrypt an mp3 file that is stored on firebase storage. I know I am targeting the correct file as I can upload it to IPFS unencrypted. However when I attempt to encrypt I am hit with this error:

"Uncaught (in promise) {message: 'Expecting Blob or File type for parameter named fi…ceived "Undefined" type instead. value: undefined', name: 'invalidParamType', errorCode: 'invalid_param_type'}"

What am I doing wrong? 
```
import lit from './lit.ts';

const songUrl = await fetch(mp3URL)
  const songData = await songUrl.blob()
  const song = new File(
    [songData],
    'Blue_Faces.mp3',
    {type: 'audio/mpeg'}
  );

  const { encryptedFile, encryptedSymmetricKey } = await lit.encrypt(song)

import LitJsSdk from 'lit-js-sdk';


const client = new LitJsSdk.LitNodeClient()
const chain = 'mumbai'

class Lit {
  private litNodeClient

  async connect() {
    await client.connect()
    this.litNodeClient = client
  }

  async encrypt(song: File) {
    if (!this.litNodeClient) {
      await this.connect()
    }

    const authSig = await LitJsSdk.checkAndSignAuthMessage({ chain })
    
    const { encryptedFile, symmetricKey } = await LitJsSdk.encryptFile(song);

**Comment by glitch003** [comment]
is this in the browser?  or node js?

**Comment by glitch003** [comment]
Hey, can you try v1.1.226 of the SDK?  I think this was a bug.  Apologies.

**Comment by bryceeaton** [comment]
> Hey, can you try v1.1.226 of the SDK? I think this was a bug. Apologies.

I managed to get it working with the help of a member of discord. The solution was putting file: songMp3 in curly brackets

const { encryptedFile, symmetricKey } = await LitJsSdk.encryptFile({file: songMp3});

**Comment by glitch003** [comment]
Oh neat, glad you figured it out!
