### ISSUE TITLE
Unable to decrypt file in browser

### ISSUE THREAD

**Issue by hnipps** [LIT-Protocol/lit-js-sdk#21]
I'm trying to decrypt a file in the browser using `LitJsSdk.decryptFile()`.

I get an error but there's no information about what happened, no description, and no error message.

I have tried the same functionality in a Node environment and it worked fine so not sure what I'm doing wrong here.

**Comment by glitch003** [comment]
hi, can you share your code?

**Comment by glitch003** [comment]
Also I accidentally pushed a bug that might have been related to this.  I just fixed it, so you can give v1.1.226 a try and see if that fixes it.

**Comment by hnipps** [comment]
Awesome, I updated the version to v1.1.226 on both server (does the encrypting) and client (does the decrypting) and it works now. Thank you @glitch003 !
