### ISSUE TITLE
Issue decrypting Blob/File

### ISSUE THREAD

**Issue by bryceeaton** [LIT-Protocol/lit-js-sdk#23]
Hi all!

I seem to have a problem decrypting the content that I was previously having issues encrypting. I am attempting to encrypt an mp3 file currently hosted on firebase storage and then uploading that encrypted content to IPFS via NFT.storage. 

I am confident the encrypting of the file worked as the file size matches what is should be ~2.1mb
I receive all the decryption shares from the lit nodes as successful however when I console.log(decryptedFile) I receive undefined. When I console.log(decryptedData) I get a Blob with a size of 9.

I have a feeling I am not handling the returned decryptedFile correctly. I believe it should be an arrayBuffer?

**App.js**
const download = async(encryptedSymmetricKey) => {

    const url = await fetch("https://bafybeib4c43fcxow6pgnnlr5vdl53t4cqm6x2ldncnypltbe2jreb6i74m.ipfs.nftstorage.link/blob")
    const encryptedFile = await url.blob()

    const { urlData } = await lit.decrypt(encryptedFile, encryptedSymmetricKey);

    const decryptedData = new File(
      [urlData],
      'Blue_Faces.mp3',
      {type: 'audio/mpeg'}
    )
    console.log({decryptedData});

};

**lit.ts**
async decrypt(encryptedFile: File, encryptedSymmetricKey: string){
    if (!this.litNodeClient) {
      await this.connect()
    }

    const authSig = await LitJsSdk.checkAndSignAuthMessage({ chain })

    const accessControlConditions = [
      {
          contractAddress: '',
          standardContractType: '',
          chain: chain,
          method: 'eth_getBalance',
          parameters: [':userAddress'],
          returnValueTest: {
          comparator: '>=',
          value: '0',  // 0 ETH, so anyone can open
          },
      },
  ]; 

  const toDecrypt = encryptedSymmetricKey
  
    const symmetricKey = await this.litNodeClient.getEncryptionKey({
      accessControlConditions,
      toDecrypt,
      chain,
      authSig,
    });

    const { decryptedFile } = await LitJsSdk.decryptFile({file: encryptedFile, symmetricKey});

    
  return {
    decryptedFile
  }
}

**Comment by glitch003** [comment]
The blob might still be right.  Blob often doesn't log correctly so make sure you double check.

**Comment by glitch003** [comment]
oops, i checked, the return value of decryptFile is def an arraybuffer.  not a blob.

**Comment by bryceeaton** [comment]
> oops, i checked, the return value of decryptFile is def an arraybuffer. not a blob.

What do I need to do to show I have the decryptedFile?

**Comment by glitch003** [comment]
I mean what do you want to do with the file?  Display it, download it?

**Comment by bryceeaton** [comment]
> I mean what do you want to do with the file? Display it, download it?

Well the bigger plan is to stream the mp3 file but my lead developer will work on that integration. For now I would like to just be able to console log something that proves I have the file. I haven't had to work with an arrayBuffer yet as I am still quite new to the coding space and just learning as I go.

**Comment by glitch003** [comment]
Did you get this resolved?
