### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by jimmywarting** [LIT-Protocol/lit-js-sdk#26]
fetch & Blob is provided by NodeJS 18 globally now. 
so it would be bad to override it.

https://github.com/LIT-Protocol/lit-js-sdk/blob/29d58eba82405d3fc4468a301ece0e9c0bbf0b4e/esbuild-nodejs-shims.js#L1-L8

I would actually suggest that you remove cross-blob and use the one provided by `node-fetch` instead.

```js
 // add fetch polyfill 
 import { webcrypto } from "node:crypto"; 

 globalThis.crypto = webcrypto; 

 if (!globalThis.fetch || !globalThis.Blob) {
   const { default: fetch, Blob } = await import('node-fetch')
   globalThis.fetch ??= fetch
   globalThis.Blob ??= Blob
 }

 ```

**Comment by glitch003** [comment]
so unfortunately an if statement there won't work, because it gets run on build time, and so the if statement checks my own nodejs version and not the one at runtime on the client.  These are good suggestions though and we will def remove them when we move to nodejs 18 as the min version.
