### ISSUE TITLE
LitJsSdk fails when I run Next.js 13 with turbopack, but no error with webpack

### ISSUE THREAD

**Issue by ChristianOConnor** [LIT-Protocol/lit-js-sdk#31]
This is the code is in my `/app/lib/litProtocolFunctions.ts` file:  
```
//@ts-ignore
import LitJsSdk from 'lit-js-sdk';
import { baseUrlConf } from '@/lib/config';

export function disconnectLit() {
    LitJsSdk.disconnectWeb3();
    return 'lit-auth';
}

export async function connectLit(uuidSpec: string) {

    const resourceId = {
        baseUrl: "http://" + baseUrlConf + ":3000",
        path: '/protected',
        orgId: "",
        role: "",
        extraData: uuidSpec
    }

    const chain = 'mumbai'
    const accessControlConditions = [
        {
            contractAddress: '<MY CONTRACT'S ADDRESS>',
            standardContractType: 'ERC721',
            chain: chain,
            method: 'balanceOf',
            parameters: [
                ':userAddress'
            ],
            returnValueTest: {
                comparator: '>',
                value: '0'
            }
        },
    ]

    const client = new LitJsSdk.LitNodeClient({ alertWhenUnauthorized: false });
    //@ts-ignore
    await client.connect();
    const authSig = await LitJsSdk.checkAndSignAuthMessage({ chain });

    //@ts-ignore
    await client.saveSigningCondition({ accessControlConditions, chain, authSig, resourceId })
    try {
        //@ts-ignore
        const litjwt = await client.getSignedToken({
            accessControlConditions, chain, authSig, resourceId: resourceId
        });
        return litjwt;
    } catch (err) {
        console.log('error: ', err);
        return 'no-token';
    }
}
```  

When I run the app in next.js 13 with webpack it works perfectly. When I run it in next.js 13 with turbopack it fails with a non-helpful error that looks like this:  
<img width="1271" alt="6wz8j" src="https://user-images.githubusercontent.com/47836708/203456056-5d94632b-1310-4992-8f0b-6dffc2f00b0c.png">

Also, it says this in my terminal (the one I used to launch the app): `Error during SSR Rendering TypeError: Class extends value #<Object> is not a constructor or null`.  

And it says this in the browser console `Uncaught ReferenceError: $RefreshSig$ is not defined`.  

**Update**  

I believe I've traced the error to it's point of failure.  
This is where the error starts:  
<img width="1264" alt="Screenshot 2022-11-22 at 8 48 12 PM" src="https://user-images.githubusercontent.com/47836708/203455669-c5e12678-700b-43e3-a4b3-bf1b3f1fecc1.png">  

And this is the line 1:332 in `node_module/lit-js-sdk/build/index.js`:  
<img width="936" alt="Screenshot 2022-11-22 at 8 50 11 PM copy2" src="https://user-images.githubusercontent.com/47836708/203455821-7036d1fe-6a31-4abd-b142-dfeb312b6d7e.png">  

So is it an issue with `h=require ("@walletconnect/ethereum-provider")`?

**Comment by GTC6244** [comment]
This is an issue /w Turbo Pack bundling - acknowledged by Vercel, and scheduled for resolution.   See similar issue here - https://github.com/aws/aws-sdk-js-v3/issues/4126 .
