### ISSUE TITLE
Document didn't update with lit-js-sdk

### ISSUE THREAD

**Issue by tonyfung99** [LIT-Protocol/lit-js-sdk#40]
I am quite confused as the document installation guide is mentioning 

`yarn add @lit-protocol/sdk-browser` 
`yarn add @lit-protocol/sdk-nodejs` 

But it seems it should be upgraded to `lit-js-sdk` already. Not sure where's the latest document located.

**Comment by glitch003** [comment]
those are the same as lit-js-sdk but only with specific features for each platform.  meaning lit-js-sdk has support for node and browser.  but @lit-protocol/sdk-browser only has browser support and @lit-protocol/sdk-nodejs only has node support.
