### ISSUE TITLE
auth signature styling

### ISSUE THREAD

**Issue by emmajane1313** [LIT-Protocol/lit-js-sdk#49]
I have succesfully set up lit protocol encryption and decryption in my next js app. My question is more of a styling issue, when awaiting the auth signature a "metamask / wallet connect" pop up occurs to sign the auth message, is there a way to change the css styling of this pop up / customise it for our website?

I couldnt find anything in the docs so wondering if its possible

Thanks :)

**Comment by glitch003** [comment]
Hi,

Yes, it should be possible.  This repo is where that popup lives: https://github.com/LIT-Protocol/lit-connect-modal

You can take a look at the CSS inside there to see what classes to modify in your own css to override things.  I think you should be able to just use the same classes in your own CSS but add `!important` to override the default css.

**Comment by emmajane1313** [comment]
cool thanks
