### ISSUE TITLE
getSignedToken doesn't support accessControlConditions for Solana

### ISSUE THREAD

**Issue by dandlezzz** [LIT-Protocol/lit-js-sdk#9]
If you call `getSignedToken` with the chain agnostic `accessControlConditions` and pass some Solana RPC filters, it returns a 422 error. However, if you use the `solRpcConditions` param, it works as expected. [The docs](https://lit-protocol.github.io/lit-js-sdk/api_docs_html/index.html#litnodeclientgetsignedtoken) seem to indicate that this method supports both, similar to `saveSigningCondition` , is this right?

**Comment by glitch003** [comment]
Hey @dandlezzz - `accessControlConditions` are EVM specific.  We have `unifiedAccessControlConditions` which is should accept Solana conditions, along with EVM and Cosmos as well.  Docs are here: https://developer.litprotocol.com/docs/AccessControlConditions/unifiedAccessControlConditions
